
CREATE TABLE IF NOT EXISTS `#__realpin_settings`
 (
  `config_id` int(11) NOT NULL AUTO_INCREMENT,
  `config_user_id` int(11) DEFAULT NULL,
  `config_name` text NOT NULL,
  `config_desc` text,
  `config_community` text,
  `config_updated` date,
  `published` int(11),
  `config_items` int(11),
  `config_space` double,
  `border_background` text,
  `background` text,
  `total_width` text,
  `total_height` text,
  `lifetime` text,
  `border` text,
  `username` text,
  `version` text,
  `license` text,
  `logo` text,
  `helptext` text,
  `helplink` text,
  `logo_link` text,
  `logo_small` text,
  `logo_small_link` text,
  `enable_postit` text,
  `enable_yt` text,
  `enable_pic` text,
  `drag` text,
  `save` text,
  `approval` text,
  `new_item` text,
  `email` text,
  `enable_jquery` text,
  `enable_jqueryui` text,
  `removal` text,
  `positioning` text,
  `maxitems` text,
  `scrollleft` text,
  `scrollright` text,
  `postit_x` text,
  `postit_y` text,
  `postit_font` text,
  `postit_font_size` text,
  `postit_font_color` text,
  `postit_font_replace` text,
  `youtube_x` text,
  `youtube_y` text,
  `yt_validate` text,
  `pic_scale` text,
  `pic_size` text,
  `pic_thumbs_size` text,
  `pic_font` text,
  `pic_font_size` text,
  `pic_font_color` text,
  `pic_border` text,
  `pic_rotate` text,
  `pic_border_color` text,
  `module_search` text,
  `module_social` text,
  `module_foreground_color` text,
  `module_background_color` text,
  `logo_enable` text,
  `helptext_enable` text,
  `logo_position` text,
  `jquery_compatibility` text,
  `pic_fancybox_info` text,
  `pic_fancybox_logo` text,
  `module_search_position` text,
  `module_social_position` text,
  PRIMARY KEY (`config_id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT IGNORE INTO `#__realpin_settings` (`config_id`, `config_user_id`, `config_name`, `config_desc`, `config_community`, `config_updated`, `published`, `config_items`, `config_space`, `border_background`, `background`, `total_width`, `total_height`, `lifetime`, `border`, `username`, `version`, `license`, `logo`, `helptext`, `helplink`, `logo_link`, `logo_small`, `logo_small_link`, `enable_postit`, `enable_yt`, `enable_pic`, `drag`, `save`, `approval`, `new_item`, `email`, `enable_jquery`, `enable_jqueryui`, `removal`, `positioning`, `maxitems`, `scrollleft`, `scrollright`, `postit_x`, `postit_y`, `postit_font`, `postit_font_size`, `postit_font_color`, `postit_font_replace`, `youtube_x`, `youtube_y`, `yt_validate`, `pic_scale`, `pic_size`, `pic_thumbs_size`, `pic_font`, `pic_font_size`, `pic_font_color`, `pic_border`, `pic_rotate`, `pic_border_color`, `module_search`, `module_social`, `module_foreground_color`, `module_background_color`, `logo_enable`, `helptext_enable`, `logo_position`, `jquery_compatibility`, `pic_fancybox_info`, `pic_fancybox_logo`, `module_search_position`, `module_social_position`) VALUES
(1, NULL, 'default_private', '', '0', '0000-00-00', 1, '', '', 'default', 'default', '600', '800', '100', '40', '0', '1.4.95', '', 'default', 'RealPin - virtuelle Pinnwand fuer dich und deine Freunde', 'https://realpin.frumania.com', 'https://realpin.frumania.com', 'default', 'https://realpin.frumania.com', '1', '1', '1', '2', '2', '0', '2', '0', '1', '1', '1', '1', '10', 'default', 'default', '200', '200', 'cartohothic-webfont.ttf', '16', '000000', '1', '280', '240', '1', '0.7', '300', '600', 'cartohothic-webfont.ttf', '26', 'FFFFFF', '12', '1', 'FFFFFF', '1', '1', 'FFFFFF', 'CCCCCC', '1', '1', 'left', '1', '1', '1', 'left', 'top'),
(2, NULL, 'default_private_global', '', '0', '0000-00-00', 1, '', '', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'false', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'false', 'false', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'false', 'true', 'false', 'false', 'false', 'false'),
(5, NULL, 'realpin_default', '', '0', '2011-01-22', 1, '', '', '000000', 'default', '600', '800', '100', '20', '0', '1.4.95', '0', 'default', 'RealPin - virtuelle Pinnwand fuer dich und deine Freunde', 'https://realpin.frumania.com', 'https://realpin.frumania.com', 'default', 'https://realpin.frumania.com', '0', '0', '0', '2', '2', '0', '2', '0', '1', '1', '1', '1', '10', 'default', 'default', '200', '200', 'cartohothic-webfont.ttf', '16', '000000', '1', '280', '240', '1', '0.8', '300', '600', 'cartohothic-webfont.ttf', '26', 'FFFFFF', '12', '1', 'ffffff', '1', '1', 'FFFFFF', 'CCCCCC', '1', '1', 'left', '1', '1', '1', 'left', 'top');

UPDATE `#__realpin_settings` SET `version` = '1.4.98' WHERE config_name!='default_private_global';

CREATE TABLE IF NOT EXISTS `#__realpin_items` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `xPos` text NOT NULL,
  `yPos` text NOT NULL,
  `type` text NOT NULL,
  `text` text NOT NULL,
  `url` text NOT NULL,
  `pw` text NOT NULL,
  `title` text NOT NULL,
  `author` text NOT NULL,
  `created` datetime NOT NULL,
  `expires` datetime NOT NULL,
  `published` tinyint(1) NOT NULL,
  `sticky` tinyint(1) NOT NULL,
  `pinboard` text NOT NULL,
  `params` text NOT NULL,
  `author_link` text NOT NULL,
  `author_email` text NOT NULL,
  `author_id` text NOT NULL,
  `rating` text NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT IGNORE INTO `#__realpin_items` (`id`,`xPos`, `yPos`, `type`, `text`, `url`, `pw`, `title`, `author`, `created`, `published`, `sticky`, `pinboard`, `params`) VALUES
('1','229', '82', 'postit', 'My first Postit!', '', 'admin', 'New #1', 'admin', '2021-01-01 00:00:00', 1, 0, '5',''),
('2','274', '231', 'youtube', '', 'https://www.youtube.com/watch?v=ta_la6vIaFc', '', 'Top Goals WM 2006', 'admin', '2021-01-01 00:00:00', 1, 0, '5','');
